[WIP] Feat/update metadata per field
samuelvanderwaal/metaboss pull request #86
Opened 2022-02-13 19:30 UTC by sunguru98

Created seperate update subcommands to support updating just the `name`, `symbol`, `creators` fields

2022-02-13 23:26 UTC, sunguru98 commented
The API and the respective test Tx are as follows

1. Name
<img width="1244" alt="Screenshot 2022-02-14 at 4 52 59 AM" src="https://user-images.githubusercontent.com/32637757/153779940-650107a6-05fa-4ffb-8748-300145d21ed1.png">
TX - https://solscan.io/tx/5eL2aq3DFMuseuhoAHhhXQhva1wpT86x6iwDHqMBsoSXzgpyJux1LVpje7N7DUoCXxhzznYtbmV7F69oWmJMcyUp?cluster=devnet

2. Symbol 
<img width="1239" alt="Screenshot 2022-02-14 at 4 54 37 AM" src="https://user-images.githubusercontent.com/32637757/153779999-1e0c1cd7-713a-4ece-865e-522b2ffa3b87.png">
TX - https://solscan.io/tx/24mHU9ywHeFPuXB3J7J6y3XfCr59DEFvWBjCXK1q67jHiaKpX3cegjZPzTUrjQFhAnCAMFMSWYX53hxSLTFXA6rs?cluster=devnet

3. Creators
<img width="1375" alt="Screenshot 2022-02-14 at 4 55 17 AM" src="https://user-images.githubusercontent.com/32637757/153780024-ada26255-231a-46d5-a3e9-df28b1ea0580.png">
TX (With custom position of 1) - https://solscan.io/tx/4v3LyzLzntoDxnjJQsWPvwRa6ebAoZkk8dhWwNXMk4xKY3PAnzFbA4MJJxfRdPtR5hHwy1mDMcViVPhvW4N8qm3P?cluster=devnet

TX (Without custom position) for index 0 - https://solscan.io/tx/3fBe3o4dmHJqiPZBcSdq8U6iGzyztFLm8bia7TYGPzTVy7HQ8GcyZMZqcsvbZf9r6oMnpHSxwQyGmbDcBT2qRUUx?cluster=devnet

2022-02-14 18:01 UTC, samuelvanderwaal commented
Awesome, thanks! I will review this tonight.

2022-02-14 18:52 UTC, sunguru98 commented
Aye aye :)

2022-02-15 05:02 UTC, samuelvanderwaal requested changes

2022-02-15 05:02 UTC, samuelvanderwaal commented on src/update_metadata.rs
> +            let _creator = std::mem::replace(&mut old_creators[*position as usize], new_creator);
`std::mem::replace` is a clever solution for swapping out creators that already exist. I think we want the API to also allow adding creators to positions that don't exist yet though. If there's a creator's array with only one creator (at position 0) I think it makes sense to allow someone to add an additional creator at position 1. What do you think?

2022-02-15 05:05 UTC, samuelvanderwaal commented
This is great work! There are just a couple of things to address and then it should be good to merge.

2022-02-20 20:54 UTC, samuelvanderwaal commented
Take a look at the changes I made and let me know if you have any questions. 

* Removed references on numbers, as primitives like `usize` are copied freely on the stack with no penalty
* Changed `u64` to `usize` to avoid the frequent casting
* Fixed off-by-one issues with the creators array length and the position
* Push creator to end of array instead of trying to index into a non-existing position

Once you're happy with the changes I'll merge.

2022-02-21 00:25 UTC, sunguru98 commented
This is perfect :) I thought we had like a mandatory requirement to just use the primitive u8 and u64 haha. Im more than happy with these filters

2022-02-21 00:40 UTC, merged